-- Migration and staging control tables (from 302_CREATE_TABLES.SQL).
-- Schema qualifiers removed. Run in the staging schema used by pkg_mg_* utilities.
-- E2B(R2) flat SRC tables for load_e2b_r2_to_src.py are in 00_create_e2b_r2_src_tables.sql.
--
-- Spool: db/logs/sql/01_create_config_tables.LOG (path is relative to SQL*Plus cwd;
--         run from db/ddl or db/run, or override: DEFINE spool_log_dir = '/your/path' before @)


SET ECHO ON;
SET TIMING ON;
SET TIME ON;

col START_TIME HEADING "START_TIME"
col START_TIME format A20
col END_TIME HEADING "END_TIME"
col END_TIME format A20

DEFINE spool_log_dir = '../logs/sql'

SPOOL &spool_log_dir./01_create_config_tables.LOG

SELECT TO_CHAR( SYSDATE, 'DD-MON-YYYY HH24:MI:SS' ) START_TIME FROM DUAL;

-- MG_CASE_LIST

CREATE TABLE MG_CASE_LIST (
    SCASENUM         VARCHAR2(100 CHAR),
    TCASENUM         VARCHAR2(100 CHAR),
    TCASEID          NUMBER,
    STATUS           NUMBER,
    ERRORS           NUMBER,
    WARNINGS         NUMBER,
    EXEC_THREAD_ID   NUMBER
);

-- MG_CODELIST_MAP

CREATE TABLE MG_CODELIST_MAP (
    CODELIST_TYPE    VARCHAR2(50 BYTE),
    CL_NAME          VARCHAR2(100 BYTE),
    S_CL_E2B_CODE    VARCHAR2(4000 BYTE),
    S_CL_E2B_DECODE  VARCHAR2(4000 BYTE),
    MAPPING_TYPE     VARCHAR2(50 BYTE),
    T_CL_CODE        VARCHAR2(4000 BYTE),
    T_CL_DECODE      VARCHAR2(4000 BYTE),
    T_CL_E2B_CODE    VARCHAR2(100 BYTE),
    T_A2_DECODE      VARCHAR2(4000 BYTE),
    COMMENTS         VARCHAR2(4000 BYTE),
    S_CL_CODE        VARCHAR2(1000 BYTE),
    S_CL_DECODE      VARCHAR2(1000 BYTE)
);

-- MG_PRODUCT_MAPPING

CREATE TABLE MG_PRODUCT_MAPPING (
    SUSPECT_DRUG_NAME        VARCHAR2(255 CHAR),
    MEDICINAL_PRODUCT        VARCHAR2(255 CHAR),
    DOSAGE_FORM              VARCHAR2(100 CHAR),
    DRUG_AUTH_COUNTRY        VARCHAR2(100 CHAR),
    DRUG_AUTH_NUMBER         VARCHAR2(100 CHAR),
    TGT_PROD_ID              NUMBER,
    SRC_FORMULATION_ID       NUMBER,
    S_LIC_COUNTRY_ID         NUMBER,
    MESSAGE                  VARCHAR2(200 BYTE),
    PM_ID                    VARCHAR2(100 BYTE),
    PROD_LIC_MAP_CMTS        VARCHAR2(1000 BYTE),
    PROD_LIC_ID              NUMBER,
    MG_PRODUCT_MAPPING       VARCHAR2(1000 BYTE),
    GENERIC_NAME             VARCHAR2(1000 BYTE),
    TGT_FAMILY_NAME          VARCHAR2(200 BYTE),
    TGT_PRODUCT_NAME         VARCHAR2(200 BYTE),
    TGT_GENERIC_NAME         VARCHAR2(500 BYTE),
    TGT_FORMULATION          VARCHAR2(200 BYTE),
    TGT_CONCENTRATION        VARCHAR2(100 BYTE),
    TGT_CONCENTRATION_UNIT   VARCHAR2(100 BYTE),
    TGT_TRADE_NAME           VARCHAR2(200 BYTE),
    TGT_LIC_NUMBER           VARCHAR2(100 BYTE),
    TGT_LICENSE_COUNTRY      VARCHAR2(100 BYTE)
);

-- MG_STUDY_PRODUCT_MAPPING

CREATE TABLE MG_STUDY_PRODUCT_MAPPING (
    STUDYNAME                VARCHAR2(200 BYTE),
    SPONSORSTUDYNUMB         VARCHAR2(200 BYTE),
    OBSERVESTUDYTYPE         VARCHAR2(100 BYTE),
    GENERIC_NAME             VARCHAR2(200 BYTE),
    SUSPECT_DRUG_NAME        VARCHAR2(200 BYTE),
    MEDICINAL_PRODUCT        VARCHAR2(200 BYTE),
    DOSAGE_FORM              VARCHAR2(100 BYTE),
    DRUG_AUTH_COUNTRY        VARCHAR2(100 BYTE),
    DRUG_AUTH_NUMBER         VARCHAR2(200 BYTE),
    MAPPING                  VARCHAR2(50 BYTE),
    TGT_STUDY_NUM            VARCHAR2(200 BYTE),
    TGT_PROTOCOL_NUM         VARCHAR2(200 BYTE),
    TGT_STUDY_TYPE           VARCHAR2(100 BYTE),
    TGT_FAMILY_NAME          VARCHAR2(200 BYTE),
    TGT_PRODUCT_NAME         VARCHAR2(200 BYTE),
    TGT_GENERIC_NAME         VARCHAR2(200 BYTE),
    TGT_FORMULATION          VARCHAR2(200 BYTE),
    TGT_CONCENTRATION        VARCHAR2(100 BYTE),
    TGT_CONCENTRATION_UNIT   VARCHAR2(50 BYTE),
    TGT_TRADE_NAME           VARCHAR2(200 BYTE),
    TGT_LIC_NUMBER           VARCHAR2(200 BYTE),
    TGT_LICENSE_COUNTRY      VARCHAR2(100 BYTE),
    SPM_ID                   VARCHAR2(50 BYTE),
    TGT_STUDY_KEY            NUMBER,
    TGT_COHORT_ID            NUMBER,
    BLINDED                  NUMBER,
    TGT_PRODUCT_ID           NUMBER,
    TGT_LICENSE_ID           NUMBER
);

-- MG_ST_SEQUENCE_MAP

CREATE TABLE MG_ST_SEQUENCE_MAP (
    SCASE_NUM    VARCHAR2(100 BYTE),
    TCASEID      NUMBER,
    STABLENAME   VARCHAR2(100 BYTE),
    TTABLENAME   VARCHAR2(100 BYTE),
    SCOLNAME     VARCHAR2(100 BYTE),
    TCOLNAME     VARCHAR2(100 BYTE),
    SSEQ         NUMBER,
    TSEQ         NUMBER
);

-- MG_CASE_ERROR_LOG

CREATE TABLE MG_CASE_ERROR_LOG (
    SCASE_NUM      VARCHAR2(50 BYTE),
    TCASE_ID       NUMBER,
    MESSAGE_TYPE   VARCHAR2(50 BYTE),
    MESSAGE        CLOB,
    THREAD_ID      NUMBER,
    DATE_AND_TIME  TIMESTAMP(6)
);

-- MG_CASE_CONST_VAL

CREATE TABLE MG_CASE_CONST_VAL (
    KEY        VARCHAR2(100 BYTE),
    VALUE      VARCHAR2(100 BYTE),
    SQL_QUERY  CLOB
);

-- MG_T_CL_INFO

CREATE TABLE MG_T_CL_INFO (
    CL_NAME         VARCHAR2(100 BYTE),
    T_CL_CODE       VARCHAR2(2000 BYTE),
    T_CL_DECODE     VARCHAR2(2000 BYTE),
    T_CL_DISPLAY    NUMBER,
    T_CL_E2B_CODE   NUMBER
);

-- MG_S_CL_INFO

CREATE TABLE MG_S_CL_INFO (
    CL_NAME         VARCHAR2(100 BYTE),
    S_CL_CODE       VARCHAR2(2000 BYTE),
    S_CL_DECODE     VARCHAR2(2000 BYTE),
    S_CL_DISPLAY    NUMBER,
    S_CL_E2B_CODE   NUMBER
);

-- MG_CL_MASTER

CREATE TABLE MG_CL_MASTER (
    CL_NAME           VARCHAR2(100 BYTE),
    S_CL_TABLE        VARCHAR2(30 BYTE),
    S_CL_CODE_COL     VARCHAR2(100 BYTE),
    S_CL_DECODE_COL   VARCHAR2(100 BYTE),
    S_WHERE_COND      VARCHAR2(4000 BYTE),
    T_CL_TABLE        VARCHAR2(30 BYTE),
    T_CL_CODE_COL     VARCHAR2(100 BYTE),
    T_CL_DECODE_COL   VARCHAR2(100 BYTE),
    T_WHERE_COND      VARCHAR2(4000 BYTE),
    ACTIVE            NUMBER,
    STATUS            NUMBER,
    S_CL_DISPLAY_COL  VARCHAR2(100 BYTE) DEFAULT NULL,
    T_CL_DISPLAY_COL  VARCHAR2(100 BYTE) DEFAULT NULL,
    T_CL_E2B_CODE_COL VARCHAR2(100 BYTE) DEFAULT NULL
);


SELECT TO_CHAR( SYSDATE, 'DD-MON-YYYY HH24:MI:SS' ) END_TIME FROM DUAL;

SET ECHO OFF;
SPOOL OFF;
